apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clinical-berth-1
spec:
  destinations:
    - server: https://kubernetes.default.svc
      namespace: ml-ops
  project: ml-ops
  source:
    repoURL: https://github.com/RamDevopspractice/clinical-berth-1.git
    targetRevision: main
    path: helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
