apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clinical-berth-1
spec:
  destinations:
    - server: https://DAE8C9167F475CC9D94D618BCCDD992A.gr7.us-west-2.eks.amazonaws.com
      namespace: ml-ops
  project: ml-ops
  source:
    repoURL: https://github.com/RamDevopspractice/clinical-berth-1.git
    targetRevision: main
    path: helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
