resources:
  requests:
    memory: "700Mi"
  limits:
    memory: "1.5Gi"
app:
  name: clinical-berth-1
replicaCount: 1
image:
  repository: 883229994922.dkr.ecr.us-west-2.amazonaws.com/clinical-bert-api
  tag: 1b4e921a3b5f35e7021cd94d7bc5e12da3923657
service:
  port: 8080
  type: ClusterIP
env:
  production: production
ingress:
  class: alb
  path: /
  pathType: Prefix
