app:
  name: clinical-berth-1
replicaCount: 1
image:
  repository: 883229994922.dkr.ecr.us-west-2.amazonaws.com/clinical-bert-api
  tag: dd8ce0a873cc805b891213d5c1e5190636f407a6
service:
  port: 8080
  type: ClusterIP
env:
  production: production
ingress:
  class: alb
  path: /
  pathType: Prefix
