app:
  name: clinical-berth-1
replicaCount: 1
image:
  repository: 883229994922.dkr.ecr.us-west-2.amazonaws.com/clinical-bert-api
  tag: 741a10698d2ac57aba89c82a165f2653d9618b6a
service:
  port: 8080
  type: ClusterIP
env:
  production: production
ingress:
  class: alb
  path: /
  pathType: Prefix
