resources:
  requests:
    memory: "512Mi"
  limits:
    memory: "1Gi"
app:
  name: clinical-berth-1
replicaCount: 1
image:
  repository: 883229994922.dkr.ecr.us-west-2.amazonaws.com/clinical-bert-api
  tag: bb40c75475e41e6494035ef34374ef63d25fc358
service:
  port: 8080
  type: ClusterIP
env:
  production: production
ingress:
  class: alb
  path: /
  pathType: Prefix
